#!/usr/bin/env python3
"""
Tool to reduce the size of Chrome trace files generated by the LLM simulator.
It merges consecutive 'decode' events for the same request into larger blocks.
"""

import json
import argparse
import sys
from typing import List, Dict, Any

def reduce_trace(input_file: str, output_file: str):
    """
    Reads a Chrome trace file, merges consecutive decode events, and writes the result.
    """
    print(f"Reading trace from {input_file}...")
    try:
        with open(input_file, 'r') as f:
            trace_data = json.load(f)
    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: Failed to decode JSON from '{input_file}'.")
        sys.exit(1)

    if "traceEvents" not in trace_data:
        print("Error: Invalid trace file format (missing 'traceEvents').")
        sys.exit(1)

    events = trace_data["traceEvents"]
    print(f"Original event count: {len(events)}")

    # Separate events by type
    other_events = []
    decode_events = []
    block_usage_events = []

    for event in events:
        if event.get("cat") == "request.decode" and event.get("ph") == "X":
            decode_events.append(event)
        elif event.get("name") == "BlockUsage" and event.get("cat") == "memory" and event.get("ph") == "C":
            block_usage_events.append(event)
        else:
            other_events.append(event)

    # Process BlockUsage events: remove consecutive duplicates
    block_usage_events.sort(key=lambda x: x.get("ts", 0))
    reduced_block_usage = []
    if block_usage_events:
        last_event = None
        for event in block_usage_events:
            if last_event is None:
                reduced_block_usage.append(event)
                last_event = event
                continue
            
            # Check if args (used_blocks, total_blocks) are same
            if event.get("args") == last_event.get("args"):
                continue
            
            reduced_block_usage.append(event)
            last_event = event
    
    if block_usage_events:
        print(f"Reduced {len(block_usage_events)} block usage events to {len(reduced_block_usage)} events.")

    # Sort decode events by pid, then name (request ID), then timestamp
    # We need to process events for each request on each engine in order
    decode_events.sort(key=lambda x: (x.get("pid", ""), x.get("name", ""), x.get("ts", 0)))

    merged_decode_events = []
    if not decode_events:
        print("No decode events found to merge.")
        merged_decode_events = []
    else:
        current_merged_event = None

        for event in decode_events:
            if current_merged_event is None:
                current_merged_event = event
                # Initialize aggregation counters if needed
                if "args" not in current_merged_event:
                    current_merged_event["args"] = {}
                # Ensure we track the number of merged steps
                current_merged_event["args"]["merged_steps"] = 1
                continue

            # Check if this event is consecutive to the current merged event
            # Criteria: same pid, same name (request ID), and starts roughly when the previous ended
            # Note: In the simulator, there might be small gaps or overlaps, but for visual reduction
            # we mainly care about grouping them if they are logically sequential.
            # Ideally, we just group all decode events for the same request on the same engine that are close in time.
            
            prev_end = current_merged_event["ts"] + current_merged_event["dur"]
            curr_start = event["ts"]
            
            # Allow a small gap (e.g., 1ms = 1000us) to account for scheduling overhead
            gap_threshold = 5000 

            is_same_context = (
                event.get("pid") == current_merged_event.get("pid") and
                event.get("name") == current_merged_event.get("name")
            )
            
            is_consecutive = (curr_start - prev_end) <= gap_threshold

            if is_same_context and is_consecutive:
                # Merge event
                # Update duration
                new_end = event["ts"] + event["dur"]
                current_merged_event["dur"] = new_end - current_merged_event["ts"]
                
                # Update args
                # We want to show the range of tokens generated
                # The 'generated_tokens_total' in the last event will be the final count
                # The 'tokens_emitted_this_step' should be summed
                
                curr_args = event.get("args", {})
                merged_args = current_merged_event.get("args", {})
                
                merged_args["merged_steps"] += 1
                merged_args["tokens_emitted_this_step"] = merged_args.get("tokens_emitted_this_step", 0) + curr_args.get("tokens_emitted_this_step", 0)
                
                # Update end-state fields from the current event
                if "generated_tokens_total" in curr_args:
                    merged_args["generated_tokens_total"] = curr_args["generated_tokens_total"]
                if "end_time_s" in curr_args:
                    merged_args["end_time_s"] = curr_args["end_time_s"]
                
                # Keep start-state fields from the first event (already in merged_args)
                
            else:
                # Push the completed merged event and start a new one
                merged_decode_events.append(current_merged_event)
                current_merged_event = event
                if "args" not in current_merged_event:
                    current_merged_event["args"] = {}
                current_merged_event["args"]["merged_steps"] = 1

        # Append the last event
        if current_merged_event:
            merged_decode_events.append(current_merged_event)

    print(f"Merged {len(decode_events)} decode events into {len(merged_decode_events)} events.")
    
    final_events = other_events + merged_decode_events + reduced_block_usage
    # Sort all events by timestamp for the final output
    final_events.sort(key=lambda x: x.get("ts", 0))
    
    trace_data["traceEvents"] = final_events
    print(f"Final event count: {len(final_events)}")

    print(f"Writing reduced trace to {output_file}...")
    with open(output_file, 'w') as f:
        json.dump(trace_data, f, indent=2)
    print("Done.")

def main():
    parser = argparse.ArgumentParser(description="Reduce Chrome trace file size by merging decode events.")
    parser.add_argument("input_file", help="Path to the input Chrome trace JSON file")
    parser.add_argument("output_file", help="Path to save the reduced Chrome trace JSON file")
    
    args = parser.parse_args()
    
    reduce_trace(args.input_file, args.output_file)

if __name__ == "__main__":
    main()
