package cmd

import (
	"fmt"
	"os"
	"path"

	homedir "github.com/mitchellh/go-homedir"
	"github.com/spf13/cobra"

	"opentela/internal/wallet"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize OpenTela: create config directory and a default wallet",
	Long: `Initializes the local OpenTela environment by:

  1. Creating the configuration directory (~/.config/opentela) if it does
     not already exist.
  2. Writing a default cfg.yaml with sensible defaults.
  3. Generating a new Solana-compatible Ed25519 keypair and storing it
     under ~/.config/opentela/accounts/<pubkey>/keypair.json.

The generated keypair can be imported into third-party wallets such as
Phantom, Solflare, or MetaMask (via Solana Snap). Run:

  otela wallet export

to obtain the private key in a format those wallets accept.

If a wallet already exists the command prints its details and exits
without overwriting anything.`,
	Run: func(cmd *cobra.Command, args []string) {
		home, err := homedir.Dir()
		if err != nil {
			fmt.Printf("Failed to determine home directory: %v\n", err)
			os.Exit(1)
		}

		// ── 1. Ensure config directory ──────────────────────────────
		configDir := path.Join(home, ".config", configDirName)
		if err := os.MkdirAll(configDir, 0o700); err != nil {
			fmt.Printf("Failed to create config directory %s: %v\n", configDir, err)
			os.Exit(1)
		}
		fmt.Printf("Config directory: %s\n", configDir)

		// ── 2. Write default config if it does not exist ────────────
		cfgPath := path.Join(configDir, "cfg.yaml")
		if _, statErr := os.Stat(cfgPath); os.IsNotExist(statErr) {
			if writeErr := writeDefaultConfig(cfgPath); writeErr != nil {
				fmt.Printf("Failed to write default config: %v\n", writeErr)
				os.Exit(1)
			}
			fmt.Printf("Default configuration written to %s\n", cfgPath)
		} else {
			fmt.Printf("Configuration file already exists at %s\n", cfgPath)
		}

		// ── 3. Wallet setup ─────────────────────────────────────────
		wm, err := wallet.NewWalletManager()
		if err != nil {
			fmt.Printf("Failed to initialize wallet manager: %v\n", err)
			os.Exit(1)
		}

		if wm.WalletExists() {
			acc, _ := wm.DefaultAccount()
			fmt.Println()
			fmt.Println("A wallet already exists:")
			fmt.Printf("  Public key:   %s\n", acc.PublicKey)
			fmt.Printf("  Provider ID:  %s\n", acc.ProviderID)
			fmt.Printf("  Keypair file: %s\n", acc.FilePath)
			fmt.Println()
			fmt.Println("No changes were made to the existing wallet.")
			return
		}

		account, err := wm.AddSolanaAccount()
		if err != nil {
			fmt.Printf("Failed to create wallet: %v\n", err)
			os.Exit(1)
		}

		fmt.Println()
		fmt.Println("✔ Wallet created")
		fmt.Printf("  Public key:   %s\n", account.PublicKey)
		fmt.Printf("  Provider ID:  %s\n", account.ProviderID)
		fmt.Printf("  Keypair file: %s\n", account.FilePath)
		fmt.Println()
		fmt.Println("This keypair is compatible with Phantom, Solflare, and the Solana CLI.")
		fmt.Println("To export for use in a third-party wallet run:")
		fmt.Println()
		fmt.Println("  otela wallet export")
		fmt.Println()
		fmt.Println("You can deposit SOL into this wallet and use it to register services")
		fmt.Println("on the OpenTela network. The wallet is loaded automatically on startup.")
	},
}

// writeDefaultConfig writes a minimal YAML configuration file.
func writeDefaultConfig(cfgPath string) error {
	content := fmt.Sprintf(`# OpenTela node configuration
# Generated by 'otela init'

seed: "%s"
port: "%s"
name: "%s"
tcpport: "%s"
udpport: "%s"

p2p:
  port: "%s"

vacuum:
  interval: %d

queue:
  port: "%s"

account:
  wallet: ""

solana:
  rpc: "%s"
  mint: "%s"
  skip_verification: %t
`,
		defaultConfig.Seed,
		defaultConfig.Port,
		defaultConfig.Name,
		defaultConfig.TCPPort,
		defaultConfig.UDPPort,
		defaultConfig.P2p.Port,
		defaultConfig.Vacuum.Interval,
		defaultConfig.Queue.Port,
		defaultConfig.Solana.RPC,
		defaultConfig.Solana.Mint,
		defaultConfig.Solana.SkipVerification,
	)

	return os.WriteFile(cfgPath, []byte(content), 0o600)
}
