name: euler-relay
seed: "99"
port: "18092"
tcpport: "18905"
udpport: "18820"
mode: full
loglevel: debug
cleanslate: true
role: relay
public-addr: "129.132.93.93"

security:
  require_signed_binary: false

solana:
  skip_verification: true

bootstrap:
  sources:
    - "https://bootstraps.opentela.ai/v1/dnt/bootstraps"
