name: euler-worker
seed: "100"
port: "8092"
tcpport: "43905"
udpport: "59820"
mode: full
loglevel: debug
cleanslate: true

service:
  name: llm
  port: "30000"

security:
  require_signed_binary: false

solana:
  skip_verification: true

bootstrap:
  sources:
    - "https://bootstraps.opentela.ai/v1/dnt/bootstraps"
